services:
  # nginx
  web:
    image: nginx:alpine3.19
    container_name: kuk-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  # php
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: kuk-app
    volumes:
      - ../:/var/www
  #mysql
  db:
    container_name: kuk-db
    image: mysql:8.0.37-bookworm
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    expose:
      - 3306
  # mailhog:
  #   container_name: kuk-mailhog
  #   image: mailhog/mailhog
  #   restart: always
  #   logging:
  #     driver: "none"
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"
